apiVersion: apps/v1
kind: Deployment
metadata:
  name: mzhtml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mzhtml
  template:
    metadata:
      labels:
        app: mzhtml
    spec:
      containers:
      - name: mzhtml
        image: mzhtml:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mzhtml-service
spec:
  selector:
    app: mzhtml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
